title: Allythy
description: >- 
baseurl: ""
url: ""

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  
sass:
    style: compressed

paginate: 8
paginate_path: /page:num/
permalink: /:title