# Site settings
title: Allythy
header-img: img/post-bg-04.jpg
#email: your-email@yourdomain.com
copyright_name: Allythy
description: "Dicas sobre o Debian, Software Livre, linha de comando"
baseurl: ""
page: "/"
#url: "http://yourdomain.com"
github_username:  allythy


# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-96197910-1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title #pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
