
title: Allythy
header-img: img/post-bg-04.jpg
copyright_name: Allythy
description: "Dicas sobre o Debian, Software Livre, linha de comando"
baseurl: ""
page: "/"
#url: "http://yourdomain.com"
github_username:  allythy

markdown: kramdown
highlighter: rouge
permalink: /:title #pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins_dir: [jekyll-paginate, jekyll-feed]

exclude:
  - vendor
